# ===== BUILD STAGE =====
FROM maven:latest AS build
WORKDIR /app
COPY CustomerServer/pom.xml .
COPY CustomerServer/src ./src
RUN mvn clean package -DskipTests

# ===== RUN STAGE =====
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Run the Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]