CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "NganhHang" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NganhHangChaId" integer,
    "TenNganhHang" text,
    CONSTRAINT "PK_NganhHang" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NganhHang_NganhHang_NganhHangChaId" FOREIGN KEY ("NganhHangChaId") REFERENCES "NganhHang" ("Id")
);

CREATE TABLE "TaiKhoanNguoiBan" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HoTen" text,
    "Email" text,
    "SoDienThoai" text,
    "MatKhauBam" text,
    "Salt" text,
    "GioiTinh" integer,
    "SinhNhat" timestamp with time zone NOT NULL,
    "NgayTao" timestamp with time zone,
    CONSTRAINT "PK_TaiKhoanNguoiBan" PRIMARY KEY ("Id")
);

CREATE TABLE "SanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NguoiBanId" integer,
    "TrangThaiSanPham" integer NOT NULL,
    CONSTRAINT "PK_SanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SanPham_TaiKhoanNguoiBan_NguoiBanId" FOREIGN KEY ("NguoiBanId") REFERENCES "TaiKhoanNguoiBan" ("Id")
);

CREATE TABLE "PhienBanSanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NganhHangId" integer,
    "SanPhamId" integer,
    "TenSanPham" text,
    "MoTaSanPham" text,
    "GiaBan" double precision,
    "NgayTao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PhienBanSanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhienBanSanPham_NganhHang_NganhHangId" FOREIGN KEY ("NganhHangId") REFERENCES "NganhHang" ("Id"),
    CONSTRAINT "FK_PhienBanSanPham_SanPham_SanPhamId" FOREIGN KEY ("SanPhamId") REFERENCES "SanPham" ("Id")
);

CREATE TABLE "MediaSanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SanPhamId" integer NOT NULL,
    "LoaiHinhAnhSanPham" integer NOT NULL,
    "Url" text,
    "NgayTao" timestamp with time zone NOT NULL,
    "PhienBanSanPhamId" integer,
    CONSTRAINT "PK_MediaSanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaSanPham_PhienBanSanPham_PhienBanSanPhamId" FOREIGN KEY ("PhienBanSanPhamId") REFERENCES "PhienBanSanPham" ("Id"),
    CONSTRAINT "FK_MediaSanPham_SanPham_SanPhamId" FOREIGN KEY ("SanPhamId") REFERENCES "SanPham" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MediaSanPham_PhienBanSanPhamId" ON "MediaSanPham" ("PhienBanSanPhamId");

CREATE INDEX "IX_MediaSanPham_SanPhamId" ON "MediaSanPham" ("SanPhamId");

CREATE INDEX "IX_NganhHang_NganhHangChaId" ON "NganhHang" ("NganhHangChaId");

CREATE INDEX "IX_PhienBanSanPham_NganhHangId" ON "PhienBanSanPham" ("NganhHangId");

CREATE INDEX "IX_PhienBanSanPham_SanPhamId" ON "PhienBanSanPham" ("SanPhamId");

CREATE INDEX "IX_SanPham_NguoiBanId" ON "SanPham" ("NguoiBanId");

INSERT INTO
    "__EFMigrationsHistory" (
        "MigrationId",
        "ProductVersion"
    )
VALUES (
        '20251014155218_Init',
        '9.0.9'
    );

COMMIT;