CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Media" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DuongDan" text,
    CONSTRAINT "PK_Media" PRIMARY KEY ("Id")
);

CREATE TABLE "NganhHang" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NganhHangChaId" integer NOT NULL,
    "TenNganhHang" text,
    "NganhHangId" integer,
    CONSTRAINT "PK_NganhHang" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NganhHang_NganhHang_NganhHangId" FOREIGN KEY ("NganhHangId") REFERENCES "NganhHang" ("Id")
);

CREATE TABLE "TaiKhoanNguoiBan" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HoTen" text,
    "Email" text,
    "SoDienThoai" text,
    "MatKhauBam" text,
    "Salt" text,
    "GioiTinh" integer,
    "SinhNhat" timestamp with time zone NOT NULL,
    "NgayTao" timestamp with time zone,
    CONSTRAINT "PK_TaiKhoanNguoiBan" PRIMARY KEY ("Id")
);

CREATE TABLE "SanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NguoiBanId" integer NOT NULL,
    "TrangThaiSanPham" integer NOT NULL,
    "TaiKhoanNguoiBanId" integer,
    CONSTRAINT "PK_SanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SanPham_TaiKhoanNguoiBan_TaiKhoanNguoiBanId" FOREIGN KEY ("TaiKhoanNguoiBanId") REFERENCES "TaiKhoanNguoiBan" ("Id")
);

CREATE TABLE "PhienBanSanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NganhHangId" integer NOT NULL,
    "SanPhamId" integer NOT NULL,
    "TenSanPham" text,
    "MoTaSanPham" text,
    "GiaBan" double precision NOT NULL,
    "NgayTao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PhienBanSanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhienBanSanPham_NganhHang_NganhHangId" FOREIGN KEY ("NganhHangId") REFERENCES "NganhHang" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PhienBanSanPham_SanPham_SanPhamId" FOREIGN KEY ("SanPhamId") REFERENCES "SanPham" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MediaSanPham" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MediaId" integer NOT NULL,
    "PhienBanSanPhamId" integer NOT NULL,
    "LoaiHinhAnhSanPham" integer NOT NULL,
    CONSTRAINT "PK_MediaSanPham" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaSanPham_Media_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Media" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaSanPham_PhienBanSanPham_PhienBanSanPhamId" FOREIGN KEY ("PhienBanSanPhamId") REFERENCES "PhienBanSanPham" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MediaSanPham_MediaId" ON "MediaSanPham" ("MediaId");

CREATE INDEX "IX_MediaSanPham_PhienBanSanPhamId" ON "MediaSanPham" ("PhienBanSanPhamId");

CREATE INDEX "IX_NganhHang_NganhHangId" ON "NganhHang" ("NganhHangId");

CREATE INDEX "IX_PhienBanSanPham_NganhHangId" ON "PhienBanSanPham" ("NganhHangId");

CREATE INDEX "IX_PhienBanSanPham_SanPhamId" ON "PhienBanSanPham" ("SanPhamId");

CREATE INDEX "IX_SanPham_TaiKhoanNguoiBanId" ON "SanPham" ("TaiKhoanNguoiBanId");

INSERT INTO
    "__EFMigrationsHistory" (
        "MigrationId",
        "ProductVersion"
    )
VALUES (
        '20251013154451_Init',
        '9.0.9'
    );

COMMIT;